CREATE TABLE TBL_BOARD (
    BNO BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(100) NOT NULL,
    CONTENT CLOB NOT NULL,
    REGDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODDATE TIMESTAMP
)

CREATE TABLE TBL_BOOKMARK (
    BNO BIGINT,
    CONSTRAINT BNO_BOOKMARK FOREIGN KEY (BNO) REFERENCES TBL_BOARD(BNO)
)