CREATE TABLE TBL_BOARD (
    BNO BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(100) NOT NULL,
    CONTENT CLOB NOT NULL,
    REGDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    BOOKMARK VARCHAR(1) DEFAULT '0'
)